### ISSUE TITLE
DAOs卡片上的发行量数值用K作为单位

### ISSUE THREAD

**Issue by Linklinkguan** [noctoid/DAO_Jam#17]
![image](https://user-images.githubusercontent.com/10827774/76072935-c8cf7a00-5fd3-11ea-91e5-2efa1fc81503.png)

**Comment by xiaotiandada** [comment]
根据需求, x < 10000 ? 不做处理  :  x / 1000 + 'K'

**Comment by xiaotiandada** [comment]
#21
