### ISSUE TITLE
在DAOs列表中增加更多数据显示

### ISSUE THREAD

**Issue by Linklinkguan** [noctoid/DAO_Jam#7]
![image](https://user-images.githubusercontent.com/10827774/75842271-d685d380-5e0a-11ea-9085-733aee4c2ccb.png)

- [ ] Fan票发行数量：xxxx票
- [ ] Fan票储备金：xxxx金币
- [ ] 参与成员数量：xxxx成员

**Comment by shellteo** [comment]
接口添加了这部分数据

**Comment by shellteo** [comment]
然后看我的毛玻璃效果
```css
  background: rgba(98,54,255,0.1);
  -webkit-backdrop-filter: blur(10px);
  backdrop-filter: blur(10px);
```
![image](https://user-images.githubusercontent.com/16064604/75978227-058a6b00-5f19-11ea-9a6d-622a9d588184.png)

**Comment by xiaotiandada** [comment]
#15
