### ISSUE TITLE
增加个人的身份标签设置和展示

### ISSUE THREAD

**Issue by Linklinkguan** [noctoid/DAO_Jam#8]
在用户的个人设置页面中增加两类选项：身份 & 技能，每类中都包含数个选项。
用户可以选择任意数量个身份，也可以不设置身份。
用户可以选择最多8个技能，并且可以给能力在1~100进行打分（为雷达图做准备），可以不填写，默认为1分。
已经添加的标签在个人主页的“信息”页面中展示，暂时不支持点击标签反查用户的功能。
![image](https://user-images.githubusercontent.com/10827774/75844451-0637da00-5e11-11ea-968f-3e48d3f7ff2b.png)

## 身份

- [ ] Designer
- [ ] Programmer
- [ ] Artist
- [ ] Cheerleader
- [ ] Manager

## 技能

- [ ]  2d art
- [ ]  3d art
- [ ]  animation
- [ ]  audio
- [ ]  game design
- [ ]  game development
- [ ]  hardware
- [ ]  marketing
- [ ]  speech
- [ ]  music
- [ ]  sing
- [ ]  frontend
- [ ]  backend
- [ ]  smart contract
- [ ]  project management
- [ ]  quality assurance
- [ ]  story and narrative
- [ ]  web design
- [ ]  writing

## 标签设置界面示意图
![image](https://user-images.githubusercontent.com/10827774/75840546-7a20b500-5e06-11ea-82c8-b1ec869f690a.png)

**Comment by shellteo** [comment]
我来做这个任务～

**Comment by shellteo** [comment]
https://andoromeda.coding.net/p/smart-signature-backend/d/smart-signature-backend/git/blob/testing/docs/dao.md
